--- 
- name: Configure all needed config for Ansible Control Plane 
  hosts: aws_ec2
  become: true
  tasks:
  - name: Update Package Manager 
    ansible.builtin.dnf:
     name: "*"
     state: latest 
  - name: Install python3-pip 
    ansible.builtin.dnf:
      name: python3-pip
      state: present 
  - name: Install ansible and boto3 
    ansible.builtin.pip:
      name: 
      - ansible
      - boto3