- name: Install Jenkins on EC2 
  hosts: ec2
  become: true 
  tasks:
  - name: add Jenkins Repo to /etc/yum.repo.d/
    ansible.builtin.get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: import key file from Jenkins-CI
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  - name: install Java and Jenkins 
    ansible.builtin.dnf:
      name:
        - java-21-amazon-corretto
        - jenkins
        - net-tools 
      update_cache: true 
  - name: start Jenkins 
    ansible.builtin.systemd_service:
      name: jenkins
      state: started

- name: Verify that Jenkins is running 
  hosts: ec2
  tasks:
  - name: Check Jenkins process 
    ansible.builtin.shell: ps aux | grep jenkins
    register: jenkins_process
  - debug: msg={{jenkins_process.stdout}}

  - name: Check Jenkins network 
    ansible.builtin.command: netstat -ltpn
    register: jenkins_network 
  - debug: msg={{jenkins_network.stdout}}




  
      