--- 
- name: Configure all needed config for Ansible Control Plane 
  hosts: tag_Name_ansible_server
  become: true
  tasks:
  - name: Update Package Manager 
    ansible.builtin.apt:
     update_cache: yes
     force_apt_get: yes
     cache_valid_time: 3600
  - name: Add Repository ppa:ansible/ansible
    ansible.builtin.apt_repository:
      repo: ppa:ansible/ansible
      state: present
  - name: Install software-properties-common
    ansible.builtin.apt:
      pkg: 
      - software-properties-common
      - ansible
      - python3-boto3
      - python3-botocore
      state: present
  - name: Copy all Ansible playbook to ansible server 
    ansible.builtin.copy:
      src: ../ansible
      dest: /home/ubuntu/
  - name: Copy private key pem 
    ansible.builtin.copy:
      src: ~/.ssh/terraform.pem 
      dest: /home/ubuntu/.ssh/
  - name: Copy AWS credentials 
    ansible.builtin.copy:
      src: ~/.aws 
      dest: /home/ubuntu/