- name: Provison EC2 Instance 
  hosts: localhost 
  vars_files:
    project-vars-ec2-instance.yaml 
  tasks:
  - name: Provsion ec2 server 
    amazon.aws.ec2_instance:
      name: "{{name}}"
      key_name: "{{key_name}}"
      image_id: "{{image_id_ubuntu}}"
      instance_type: "{{instance_type}}"
      security_group: "{{security_group}}"
      subnet_id: "{{subnet_id_public}}"
      network_interfaces:
        - assign_public_ip: "{{assign_public_ip}}"
    register: ec2_status
  - debug: msg={{ec2_status["instances"][0]["public_ip_address"]}} 
